export const SPACES = [
  {
    id: 1,
    name: "Desk A1",
    type: "Standing Desk",
    capacity: 1,
    x: 10,
    y: 10,
  },
  { id: 2, name: "Desk A2", type: "Regular Desk", capacity: 1, x: 10, y: 30 },
  { id: 3, name: "Desk A3", type: "Regular Desk", capacity: 1, x: 10, y: 50 },
  {
    id: 4,
    name: "Desk B1",
    type: "Standing Desk",
    capacity: 1,
    x: 30,
    y: 10,
  },
  { id: 5, name: "Desk B2", type: "Regular Desk", capacity: 1, x: 30, y: 30 },
  { id: 6, name: "Desk B3", type: "Regular Desk", capacity: 1, x: 30, y: 50 },
  {
    id: 7,
    name: "Meeting Room 1",
    type: "Conference Room",
    capacity: 6,
    x: 60,
    y: 10,
    width: 30,
    height: 20,
  },
  {
    id: 8,
    name: "Meeting Room 2",
    type: "Conference Room",
    capacity: 4,
    x: 60,
    y: 40,
    width: 30,
    height: 20,
  },
];
